config/routes.rb
Rails.application.routes.draw do
  get 'jirous/create'
  get 'jirous/index'
  get 'relationships/create'
  get 'relationships/destroy'
  get 'users/index'
  get 'notifications/index'
  get 'microposts/index'
  
  
  get 'jirous/post'
  post 'jirous/word'
  get 'jirous/word', to: 'jirous#search'
  get 'jirous/search'
  post 'jirous/create'
  get 'jirous/shoplist'
  get 'jirous/wordlist'
  delete 'jirous/:id' , to: 'jirous#destroy'

  root to: "home#index"
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :microposts,only: [:index, :show, :create, :destroy, :edit] do
  resources :comments, only: [:create] 
  end
  resources :microposts,only: [:index, :show, :create, :destroy, :edit] do
  resources :likes, only: [:create, :destroy]
  end
  resources :notifications, only: :index
  resources :relationships,       only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
   protect_from_forgery
  require 'net/http'
  require 'uri'
  require 'json'
  def index
    if user_signed_in?
    @micropost = current_user.microposts.build
    @feed_items = current_user.feed.paginate(page: params[:page],:per_page => 5)
    @jirou = current_user.jirous
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<%if user_signed_in? %>
  <div class="row">
    <div class="col-lg-4 col-md-6 col-sm-12 ml-auto mr-auto">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
       <section class="stats">
        <%= render 'shared/stats' %>
      </section>
      <section class="micropost_form">
        <%= render 'shared/micropost_form' %>
      </section>
      <section class="mymeshi">
      <%= render 'shared/myjirou' %>
      </section>
    </div>
    <div class="col-lg-4 col-md-6 col-sm-12 ml-auto mr-auto">
      <h3>みんなのつぶやき</h3>
      <%= render 'shared/feed' %>
    </div>
    <div class="col-lg-4 col-md-6 col-sm-12 ml-auto mr-auto">
      <h3>お店を検索してmyメシに加えよう！</h3>
      <%= link_to "店名で検索",   "/jirous/post" %><br/>
      <%= link_to image_tag("/assets/shopname.jpg", :size =>'360x240'), "/jirous/post" %><br/>
      <%= link_to "キーワード検索",   "/jirous/search" %><br/>
      <%= link_to image_tag("/assets/rename2.jpg", :size =>'360x240'), "/jirous/search" %>
    </div>

  </div>
   <%= render 'shared/notifications' %>
<% else %>
  <div class="center jumbotron">
    <h1>Meshistagram</h1>

    <h2>
      こだわりのメシを投稿して、お店を共有しよう！
    </h2>
    <div style="text-align:center;"></br>
    <%= link_to "登録する！", "/users/sign_up", class: "btn btn-lg btn-warning" %>
    <%= form_for(User.new, url:user_session_path) do |f| %>
  <%= f.hidden_field :email, value: "example@railstutorial.org" %>
  <%= f.hidden_field :password, value: "foobar" %>
  <%= f.submit "かんたんログイン", class:"btn btn-lg center-block btn-success"%> 
<% end %>
<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to t('.Facebookでログイン', provider: OmniAuth::Utils.camelize(provider)), omniauth_authorize_path(resource_name, provider), class: "btn btn-lg btn-primary" %><br />
  <% end -%>
<% end -%>
    </div>

  </div>

  
<% end %>