config/routes.rb
Rails.application.routes.draw do
  get 'jirous/create'
  get 'jirous/index'
  get 'relationships/create'
  get 'relationships/destroy'
  get 'users/index'
  get 'notifications/index'
  get 'microposts/index'
  
  
  get 'jirous/post'
  post 'jirous/word'
  get 'jirous/word', to: 'jirous#search'
  get 'jirous/search'
  post 'jirous/create'
  get 'jirous/shoplist'
  get 'jirous/wordlist'
  delete 'jirous/:id' , to: 'jirous#destroy'

  root to: "home#index"
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :microposts,only: [:index, :show, :create, :destroy, :edit] do
  resources :comments, only: [:create] 
  end
  resources :microposts,only: [:index, :show, :create, :destroy, :edit] do
  resources :likes, only: [:create, :destroy]
  end
  resources :notifications, only: :index
  resources :relationships,       only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "ホームに戻る",   root_path %></li>
      <li><%= link_to "店名で検索",   "/jirous/post" %></li>
      <li><%= link_to "キーワード検索",   "/jirous/search" %></li>
      <li><%= link_to "ログアウト", destroy_user_session_path, :method => :delete%></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="row">
    <div class="col-lg-4 col-md-6 ml-auto mr-auto">
      <%= link_to image_tag("meshilogo.jpg"), root_path, id: "logo" %>
    </div>
    <div class="col-lg-4 col-md-6 ml-auto mr-auto">
      <ul>
        <% if signed_in? %>
          <li><%= link_to "ユーザ一覧", users_path %></li>
          <li><%= link_to "プロフィール", current_user %></li>
          <li><%= link_to "ユーザ設定", edit_user_path(current_user) %></li>
        <% else %>
          <li><%= link_to t(".ログイン"), new_session_path(resource_name) %></li>
        <% end %>
      </ul>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Meshistagram</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
<% if notice %>
  <p class="notice"><%= notice %></p>
<% elsif alert %>
  <p class="alert"><%= alert %></p>
<% end %>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>